cd ./aurelia-packages/animator-css
npm install 
cd ../../
cd ./aurelia-packages/binding
npm install 
cd ../../
cd ./aurelia-packages/bootstrapper
npm install 
cd ../../
cd ./aurelia-packages/dependency-injection
npm install 
cd ../../
cd ./aurelia-packages/event-aggregator
npm install 
cd ../../
cd ./aurelia-packages/framework
npm install 
cd ../../
cd ./aurelia-packages/history
npm install 
cd ../../
cd ./aurelia-packages/history-browser
npm install 
cd ../../
cd ./aurelia-packages/html-template-element
npm install 
cd ../../
cd ./aurelia-packages/http-client
npm install 
cd ../../
cd ./aurelia-packages/loader
npm install 
cd ../../
cd ./aurelia-packages/loader-default
npm install 
cd ../../
cd ./aurelia-packages/logging
npm install 
cd ../../
cd ./aurelia-packages/logging-console
npm install 
cd ../../
cd ./aurelia-packages/metadata
npm install 
cd ../../
cd ./aurelia-packages/path
npm install 
cd ../../
cd ./aurelia-packages/route-recognizer
npm install 
cd ../../
cd ./aurelia-packages/router
npm install 
cd ../../
cd ./aurelia-packages/task-queue
npm install 
cd ../../
cd ./aurelia-packages/templating
npm install 
cd ../../
cd ./aurelia-packages/templating-binding
npm install 
cd ../../
cd ./aurelia-packages/templating-resources
npm install 
cd ../../
cd ./aurelia-packages/templating-router
npm install 